name: Build Distribution

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build distribution
        run: npm run build
      
      - name: Archive distribution
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  package:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      
      - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
        # Only run on main branch push (e.g. after pull request merge).
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "<${{ github.actor }}@users.noreply.github.com>"
          git commit -a -m "Update Dist Folder"
          git push
      #- name: Create Pull Request
      #  uses: peter-evans/create-pull-request@v5
      #  with:
      #    token: ${{ secrets.TOKEN }}
      #    branch: main
      #    title: Update Dist Folder
      #    body: Automated update of the dist folder
      #    committer: GitHub <noreply@github.com>
      #    author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
     