name: Build Distribution

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'

  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build distribution
        run: ncc build src/index.js 
      
      - name: Archive distribution
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  package:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      
      - name: git push dist folder
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "<${{ github.actor }}@users.noreply.github.com>"
          git commit -a -m "[bot] Update Dist Folder"
          git push
